trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '2fae94b1-7a9f-489c-bf7c-877563309b5c'
  resourceGroup: 'rg-tpr-app-use-001'
  location: 'East US'
  vmPrefix: 'vm-prod-'
  vmNameSuffixes: '["managerapp","mirth","winsrv"]'
  nsgPrefix: 'nsg-prod-'
  nicPrefix: 'nic-prod-'

stages:
- stage: Deploy
  jobs:
  - job: DeployInfrastructure
    steps:
    - script: |
        echo "Setting Azure subscription to $(azureSubscription)"
        az account set --subscription "$(azureSubscription)"
        
        echo "Current subscription:"
        az account show
        
        echo "Creating resource group $(resourceGroup) in location $(location)"
        az group create --name $(resourceGroup) --location $(location)
        
        echo "Verifying resource group $(resourceGroup)"
        az group show --name $(resourceGroup) --output table
        
        echo "Deploying Bicep templates"
        az deployment group create \
          --resource-group $(resourceGroup) \
          --template-file Spoke-Modules/infra/main.bicep \
          --parameters vmPrefix=$(vmPrefix) \
                       vmNameSuffixes='$(vmNameSuffixes)' \
                       adminUsername='gssadmin' \
                       adminPassword='$Perot20304050' \
                       nsgPrefix=$(nsgPrefix) \
                       nicPrefix=$(nicPrefix)
      displayName: 'Deploy Infrastructure'
      failOnStderr: true
