# azure-pipelines.yml
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Shail-Subs'  # Replace with your Azure subscription name
  resourceGroupName: 'my-rg-functionapp'
  location: 'East US'
  storageAccountName: 'mystorageaccount'
  functionAppName: 'myfunctionapp'
  appServicePlanName: 'my-app-service-plan'
  dotnetVersion: 'v6.0'

stages:
- stage: DeployInfrastructure
  jobs:
  - job: Deploy
    displayName: 'Deploy Azure Function App with Bicep'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Create Resource Group (if not exists)
          az group create --name $(resourceGroupName) --location $(location)

          # Deploy Bicep Template with variables
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file $(System.DefaultWorkingDirectory)/main.bicep \
            --parameters resourceGroupName=$(resourceGroupName) \
                         location=$(location) \
                         storageAccountName=$(storageAccountName) \
                         functionAppName=$(functionAppName) \
                         appServicePlanName=$(appServicePlanName) \
                         dotnetVersion=$(dotnetVersion)
