trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  RESOURCE_GROUP: 'policy-Notts-rg'
  LOCATION: 'East US'
  azureSubscription: 'Shail-Subs'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Ensure Azure CLI is updated to the latest version
      az upgrade --yes

      # Create resource group if it doesn't exist
      az group create --name $RESOURCE_GROUP --location "$LOCATION"

      # Deploy the main Bicep template
      az deployment group create \
        --resource-group $RESOURCE_GROUP \
        --template-file main.bicep
  displayName: 'Deploy Bicep Template'