trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Shail-Subs'
  resourceGroupName: 'NOtts-RG'
  location: 'eastus'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Login to Azure
      az account set --subscription $(azureSubscription)

      # Create Resource Group if it doesn't exist
      az group create --name $(resourceGroupName) --location $(location)

      # Deploy the Bicep template
      az deployment group create \
        --resource-group $(resourceGroupName) \
        --template-file main.bicep \
        --parameters storageAccountName=youruniquestorageaccountname
  displayName: 'Deploy Bicep Template'
