trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Shail-Subs'  # Replace with your Azure subscription name
  resourceGroupName: 'functionapp-conn2-rg'
  location: 'East US'
  storageAccountName: 'nottsmystorageaccount02'
  functionAppName: 'FunctionAppResponder'
  appServicePlanName: 'my-app-service-plan'
  dotnetVersion: 'v6.0'  # Ensure this matches the runtime you want to deploy
  vnetName: 'my-vnet02'
  subnetName: 'my-subnet02'
  vnetAddressPrefix: '10.0.0.0/16'
  subnetAddressPrefix: '10.0.1.0/24'

stages:
- stage: DeployInfrastructure
  jobs:
  - job: Deploy
    displayName: 'Deploy Azure Function App with VNet Integration'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Create Resource Group
          az group create --name $(resourceGroupName) --location "$(location)"

          # Deploy Bicep Template
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file $(System.DefaultWorkingDirectory)/main.bicep \
            --parameters location="$(location)" \
                         storageAccountName=$(storageAccountName) \
                         functionAppName=$(functionAppName) \
                         appServicePlanName=$(appServicePlanName) \
                         dotnetVersion=$(dotnetVersion) \
                         vnetName=$(vnetName) \
                         subnetName=$(subnetName) \
                         vnetAddressPrefix=$(vnetAddressPrefix) \
                         subnetAddressPrefix=$(subnetAddressPrefix)
