trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Shail-Subs'
  resourceGroupName: 'Nottscounty2-rg'
  location: 'eastus'
  storageAccountName: 'nottscounty01010202'
  vnetName: 'notts-vnet'
  firewallName: 'nottsfw'
  gatewayName: 'appGWnotts'
  appGatewayName: 'mynewappgw01'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Login to Azure
      az account set --subscription $(azureSubscription)

      # Create Resource Group if it doesn't exist
      az group create --name $(resourceGroupName) --location $(location)

      # Deploy the Bicep template
      az deployment group create \
        --resource-group $(resourceGroupName) \
        --template-file main.bicep \
        --parameters storageAccountName=$(storageAccountName) vnetName=$(vnetName) firewallName=$(firewallName) gatewayName=$(gatewayName) appGatewayName=$(appGatewayName) location=$(location)
  displayName: 'Deploy Bicep Template'
