trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Shail-Subs'
  resourceGroupName: 'rg-tpr-app-use-001'
  location: 'eastus'

stages:
- stage: Deploy
  jobs:
  - job: DeployInfrastructure
    displayName: 'Deploy infrastructure'
    variables:
      - group: VMSecrets
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create the resource group if it doesn't exist
          az group create --name $(resourceGroupName) --location "$(location)"
          # Deploy the Bicep template
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file bicep/main.bicep \
            --parameters adminUsername=$(adminUsername) adminPassword= '$Perot20304050' location="$(location)"
      displayName: 'Deploying Bicep Template'
