trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Shail-Subs'
  resourceGroupName: 'rg-tpr-app-use-001'
  location: 'eastus'

stages:
- stage: Deploy
  jobs:
  - job: DeployInfrastructure
    displayName: 'Deploy infrastructure'
    variables:
      - group: VMSecrets
    steps:
    - task: TerraformInstaller@0
      inputs:
        terraformVersion: '1.5.0'  # Specify the version of Terraform

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Initialize Terraform
          cd terraform
          terraform init

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Create the resource group if it doesn't exist
          az group create --name $(resourceGroupName) --location "$(location)"

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Plan the Terraform deployment
          cd terraform
          terraform plan -out=tfplan

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Apply the Terraform plan
          cd terraform
          terraform apply "tfplan"
      displayName: 'Deploying Terraform Infrastructure'
